### ISSUE TITLE
Please provide xpi for 0.2.6

### ISSUE THREAD

**Issue by polyzen** [EFForg/privacybadgerfirefox#287]
Version was bumped to 0.2.6, but the latest available xpi is 0.2.5.

[This package script](https://aur.archlinux.org/packages/firefox-extension-privacybadger) relies on the addon being under https://s.eff.org/files.

**Comment by cooperq** [comment]
Hi, so the reason I haven't published it is that 0.2.6 is not that different from 0.2.5, I mainly had to change the version to try to get it published in AMO. I will upload a new version when I make another release, is there a way that your script can look at the file at https://www.eff.org/files/privacybadger-latest.xpi for version changes instead of the head of the git repo?

**Comment by cooperq** [comment]
My concern is that I might update the version without making a new release sometimes, and I don't want to break your script.

**Comment by polyzen** [comment]
The version set by the pkgbuild script is static; so using the latest.xpi would be misleading. Certainly doable. Currently it pulls from [here](https://s.eff.org/files/privacy-badger-0.2.5.xpi)

I should've just checked the changes before opening an issue haha
