### ISSUE TITLE
Privacy Badger gone from Toolbar

### ISSUE THREAD

**Issue by JBird4049** [EFForg/privacybadgerfirefox#316]
I can see, and turn on/off, Privacy Badger in the Add-ons Manager, but it has disappeared from the Firefox Toolbar, and is no longer shown as an option in the Firefox toolbar customization box. This started a few days ago.  I am using Firefox 36.0.1

**Comment by tonyclayton** [comment]
I have exactly the same problem

**Comment by tonyclayton** [comment]
I have removed Privacy badger, and then reloaded it. This restored the icon.

**Comment by JBird4049** [comment]
I tried that, but it is still is not appearing.  Thanks, though.

**Comment by romexpat** [comment]
Disappeared from my toolbar also (Firefox 36.0.1, Linuxmint 17.1). Stilll doesn't reappear after re-installation, nor after full re-installation of firefox. It is visible in the Add-ons Manager, but not in the customization box.

**Comment by GAllen8** [comment]
I'm also experiencing this issue with Firefox 36.0.1.  I noticed that Duolingo wasn't posting updates to Facebook which happens when Privacy Badger blocks Facebook.  That's when I looked for the button and realized it wasn't there.  I reset Firefox, reinstalled Privacy Badger and the menu button still doesn't display.  I finished a section on Duolingo and it correctly updated my Facebook page.  This leads me to believe that Privacy Badger is installed and running, i.e. the new installation hasn't flagged Facebook yet.

**Comment by romexpat** [comment]
Thanks for the information - I'm afraid I am not really an expert on this -
more of a user, but I take this kind of security seriously. I don't know
what Dualingo is, so forgive my ignorance. I also believe PB is installed
and running, because it appears under the Addons menu item - I just can't
see it on the menu bar as usual - I don't normally mess about with things
like trackers - if they are identified as trackers by PB, they get blocked,
so I miss the facility to manually block possible trackers.


The above applies to my desk machine. I also have a laptop running FF
36.0.0, and that does not have the problem, PB is OK. Last night there was
a LinuxMint update which called for installation of FF 36.0.1, but I
blocked that, so I hope there is a solution soon.

Incidentally, I saw somewhere that major nuisances like Facebook, Amazon,
Google etc are trying to get the people who produce Adblock to let their
adverts through
 - don't let them do this with PB!

Best Regards,
KW

**Comment by indivisible** [comment]
I, too, had this issue. Building from latest git solved it. Looks like they only have to push out a new version to AMO.

**Comment by romexpat** [comment]
Thanks for that -I'll be patient!

**Comment by cooperq** [comment]
Downloading the latest version of privacy badger from https://www.eff.org/pb will solve this problem. AMO is not up to date, I need to get the latest version uploaded to the mozilla addons site.

**Comment by romexpat** [comment]
Great - working fine on FF 36.0.4
