### ISSUE TITLE
cannot log into wordpress 4.22 when privacy badger is activated

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [EFForg/privacybadgerfirefox#350]
Hello,

since wordpress 4.22 and maybe 4.1 we cannot log into wordpress anymore if privacy badger is activated. 

you enter your user and password but go back the same login page again and again

Cheers

**Comment by cooperq** [comment]
@bilbo-the-hobbit can you send me a screenshot showing which domains privacy badger is blocking when you try to log in?

**Comment by bilbo-the-hobbit** [comment]
Hello,

its our company website www.opensides.be i join two screenshot front page and login page

![opensides be](https://cloud.githubusercontent.com/assets/243766/7817596/4d49ed60-03d6-11e5-82d3-b319bcafb82a.png)
![privacy-badger-wordpress](https://cloud.githubusercontent.com/assets/243766/7817597/4d795c08-03d6-11e5-8586-9f1bc67ba0df.png)

**Comment by cooperq** [comment]
Sorry for the misunderstanding! I need a screenshot with the privacy badger menu open so that I can see what exactly is being blocked on your domain. Or you can tell me all the domians listed in the privacy badger menu and what their status is (red, yellow, or green). You can see the privacy badger menu by clicking on the privacy badger icon in the top right of your browser. Thanks.

**Comment by bilbo-the-hobbit** [comment]
hello,

tested with the release 1.0.0, the bug is gone

Cheers
