### ISSUE TITLE
Mozilla Addons/Extension Signing

### ISSUE THREAD

**Issue by tr37ion** [EFForg/privacybadgerfirefox#358]
Please adopt Privacy Badger to upcoming Mozilla Addons/Extension Signing project. Your AddOn is already marked as *untrusted* with Firefox Developer Edition 40.0a2.

See: https://wiki.mozilla.org/Addons/Extension_Signing

**Comment by cooperq** [comment]
We do plan to do this, thanks.

**Comment by tr37ion** [comment]
Great and thanks for this nice addon :)

**Comment by ericschultz** [comment]
Just an FYI, as of August 4, the Developer Edition of Firefox is blocking Privacy Badger from being enabled because it's not signed. It would be nice if this was fixed pretty quickly :)

**Comment by albill** [comment]
I just opened an issue on this and then saw this.

As of this coming Tuesday (August 11), Firefox 41 will be the Beta branch and all Beta, Web Developer, and Nightly users will be blocked from running it since it still isn't signed. Six weeks from that point, 41 will become the public release for everyone and no one will be able to install it.

I suggest someone might wish to prioritize this task forward.

**Comment by nyuszika7h** [comment]
@abill Are you saying `xpinstall.signatures.required` will be removed even from Nightly on August 11? That's the most ridiculous thing I've ever heard.

**Comment by X-dark** [comment]
@nyuszika7h That is wrong. Nightly and Dev will keep the ability to disable signature checking:
> Firefox Release and Beta versions will not have any way to disable signature checks. Checks can be disabled in other versions, as described in detail below. 
> https://wiki.mozilla.org/Addons/Extension_Signing#FAQ

For a reason while signing the extension is not a straightforward process, I suggest you to read this: https://github.com/EFForg/https-everywhere/issues/2051#issuecomment-123863995

**Comment by nyuszika7h** [comment]
Oh, okay. Nightly already started blocking unsigned extensions by default for me, and I disabled that "feature".

**Comment by tr37ion** [comment]
You may ask at irc.mozilla.org #amo or #firefox if there are questions on the signing process.

**Comment by cooperq** [comment]
Thanks. We are working with the team at Mozilla to address some issues and concerns with the signing process.

**Comment by mdegroot-bnv** [comment]
Also ran into this issue today and had to search for a solution to disable this signature checking. Hopefully it will be resolved before the option to disable the signature check is removed.

**Comment by stephaniehobson** [comment]
I'm running Beta and noticed today it's been disabled for me here.

**Comment by getconor** [comment]
I understand you've been working with Mozilla on this since at least 41.0b1. Just wanted to say that since shortly after 41.0b1 was released, and even now on 41.0b3, Firefox keeps trying to download an update for the disabled PB plugin that is dated 2015-08-07. This always fails with the message "There was an error downloading Privacy Badger."

**Comment by cooperq** [comment]
It's all signed now!
