### ISSUE TITLE
Crash with Disqus

### ISSUE THREAD

**Issue by blobgo** [EFForg/privacybadgerfirefox#422]
I have the problem that Firefox always crashes if I try to login into Disqus from a third-party website.

To reproduce:
1. Visit a site which uses Disqus.
2. Write a comment.
3. Click to login via Disqus.
4. A new window opens and you are being logged in.
5. Sometimes (but very rarely) you see this message a short time afterwards:
![privacybadgerdisqus](https://cloud.githubusercontent.com/assets/12105354/8762038/a8e6b660-2d6d-11e5-9b2a-cb205621497e.PNG)
6. Firefox crashes before I'm even able to choose any option. (And additionally it also often shows the message that the plugin container crashed too)

I've submitted many crash reports to Mozilla via the internal crash reporter, so if you find them you should be able to use them and for detailed analysis.

0.26
Firefox 39.0
Windows 7

**Comment by blobgo** [comment]
Thanks, @cooperq.
So this is fixed in v 0.99?

Is this version already available on the website?
Or does Privacy Badger update automatically?

**Comment by cooperq** [comment]
Yes this is fixed in 0.99 (and 1.0 which is out in a week!)
0.99 was only up for a short time as a beta test for 1.0 so if your browser didn't already upgrade to it automatically, it won't until we release 1.0 
*But* you can download privacy badger 0.99 from here if you like:
http://www.eff.org/files/privacy-badger-0.99.xpi
