### ISSUE TITLE
Options Page Freezing with Every User Interaction

### ISSUE THREAD

**Issue by jdorenbush** [EFForg/privacybadgerfirefox#465]
Firefox freezes for 15+ seconds with each user interaction on the Options page (options.html).

- Scrolling through list of tracker domains on "Filter Settings" tab causes Firefox to hang
- Adding and removing domains from the "Whistlisted Domains" tab causes temporary freeze

*Ubuntu 14.04 / Firefox 40.0 / Privacy Badger 1.0.0*

**Comment by nekromoff** [comment]
confirmed on ff 39.0, ubuntu 14.04.
seems to be caused by site list loader that completely blocks firefox.

**Comment by SwartzCr** [comment]
@nekromoff can you be more descriptive with what you mean by 'site list loader'?

**Comment by nekromoff** [comment]
just during the website list loading the whole browser freezes

**Comment by cooperq** [comment]
Can confirm that this is happening

**Comment by cypherpunk** [comment]
I too am experiencing this. FF 40.0 Ubuntu 14.04. As soon as the Badger's over 1300 tracking domains load in Options, I get an unresponsive script warning for "Script: resource://gre/modules/commonj…/jquery-ui/js/jquery-1.10.2.js:762" and FF goes unresponsive except for repeated such warnings whether I hit stop or continue. When I hit debug, a debugger shows up at the bottom of the browser but it gives no useful information up front and I don't know how to use it to get you something helpful. FF does, however, become responsive again, allowing me to close the PB Options tab or navigate to other tabs so long as the debugger is up.

I'd be glad to follow any instructions you can give me to help you get more info to debug this; I'll keep checking back here.

-Mo

**Comment by nekromoff** [comment]
still freezing on 1.0.1

**Comment by cooperq** [comment]
Yep, I haven't been able to fix this yet. Sorry.

**Comment by cypherpunk** [comment]
My Matrox Parhelia used for DPI precision, while being unmatched at what it does, has no hardware acceleration for anything later then 2004, so everything "modern" like flash is handled strictly by CPU power. Sometimes when in weekly long uptime without refresh, FF/flash can show signs of latency. So I thought, possibly PB slowing in Option menu : https://github.com/EFForg/privacybadgerfirefox/issues/487

due to my own peculiar setup, glad to learn it is not. I suppose depending on you CPU power  it takes less then five seconds while PB’s Options are available. Then I can scroll up and down without any delays. There is latency of five seconds, at least in my case,  each time you move rule slider. Then each takes five seconds for menu to be accessible again.

Mark

**Comment by mlissner** [comment]
I'm guessing something like this could be a good solution: http://w2ui.com/web/blog/7/JavaScript-Grid-with-One-Million-Records

Basically, rather than render the entire table at once, render it as the user scrolls. In the demo there, they have a table with 1M rows that performs admirably.

**Comment by cypherpunk** [comment]
When you open Options and you find six hundreds or more tracking domains, and you learn that at least 40% are in green mode, things are not pleasant or easy. In order to sort them all to your liking,
with CPU hog issue, this would takes hours.

Until this is sorted, but also generally speaaking, have you considered making global setting rule for all domains in Option settings?  It would be some much easier if we could tag all domains in Yellow or Red, specially with CPU hog issue.
