### ISSUE TITLE
Not working with Tor?

### ISSUE THREAD

**Issue by jfml** [EFForg/privacybadgerfirefox#467]
I'd be happy to give information about this if somebody tells me how but PB doesn't seem to work with TorBrowser for me. It just stays on „Loading“ forever (and there's two badgers, the greyed out one and the „active“ one). 

It works fine on regular FF for me and aside of NoScript which I disabled for testing I seem to have the same plugins with both browsers (cept for TorButton / TorBrowser).

**Comment by Anonymity-Rocks** [comment]
I'm using Firefox for Mac and am having the exact same problem. (See screenshot.) Everything worked nicely until the update this morning. :( Now, I'm hesitant to even check my email, since, according to the new tutorial, the default setting apparently green-lights cookies and trackers.
![screen shot 2015-08-07 at 9 05 41 am](https://cloud.githubusercontent.com/assets/13694626/9136244/114fecd8-3ce3-11e5-931a-ae30d3f8ef9a.png)

**Comment by jfml** [comment]
So you are not using Tor? On regular Firefox (39.0.3) it's working for me.

My TorBrowser is 4.5.3 (based on Mozilla Firefox 31.8.0), btw.

**Comment by cooperq** [comment]
PLEASE DON'T USE PRIVACY BADGER WITH TOR BROWSER. 
You are compromising your anonymitiy by making changes to the tor browser, you are made more fingerprintable and (ironically) more trackable. You should not modify the default settings of Tor browser.

**Comment by jfml** [comment]
Ok, fair enough. I read that somewhere else too and have already disabled it ^__^

**Comment by cooperq** [comment]
:) Sorry, I would love for it to be a thing in TBB but for now it's definitely not good for privacy. I'm glad you like it though!

**Comment by jfml** [comment]
Yeah, it's aweome! Keep up the good work!
