### ISSUE TITLE
Privacy Badger now breaks Google maps

### ISSUE THREAD

**Issue by not-so-gnubie** [EFForg/privacybadgerfirefox#501]
Here is something I think you should know about.

I have been using Privacy Badger for a while now.  A few days ago I went to maps.google.com to get a map.  All that showed was a box for putting in an address and a couple of buttons on a white background.  That's it.  I had not changed anything.  The satellite maps still worked, but the road maps just gave a while background.  The problem persisted.  I went to MapQuest.  That didn't work either.  I wondered if it was Privacy Badger so I turned it off for MapQuest and reloaded the page.  It worked.  Then I went to Google Maps, turned off Privacy Badger and reloaded.  Now it worked.  I think somewhere in there I had to clear the browser's cache too.

Google Maps must have changed something which Privacy Badger then erroneously tripped over.  You might want to take a look.  It won't be good for Privacy Badger if it breaks a heavily used page like Google Maps.

Jeff Barry

PS I run Firefox on Linux.

**Comment by cypherpunk** [comment]
Confirming bug on Firefox in Windows 7 as well. Maps were working yesterday and do not work today. Disabling Privacy Badger enables Google Maps to work again.

**Comment by cypherpunk** [comment]
@Jeff,

Far from suggesting, that this should not be resolved. But, consider for how many Google scripts you already have to give permission, in order to have any function of Gmaps.

And using PB means, you already use at least a few more privacy tool, since they are all set, what is the point of giving them permission for something so intrusive like Gmaps?

Have you consider using portable Browser on USB, or on virtual OS, dedicated for such purpose, it will save you a lots of time and hassle when you really need things like Gmaps.

Just a thought

**Comment by not-so-gnubie** [comment]
>> Have you consider using portable Browser on USB,
>> or on virtual OS, dedicated for such purpose

No.  It's not a question of what I can or cannot do on my machine.  We have such a massive eSecurity problem on this planet because there are a whole lot of people out there who don't even understand the problem, let alone what to do about it.  However if they get to the point where they actually try to use a security tool like Privacy Badger then that too should be as simple as possible to use and not require them to jump through hoops because, if it does, they will not only drop the tool but they will be less likely to try other measures to protect themselves.

>> And using PB means, you already use at least a few more privacy tools

I do.  And I qualify as a geek.  But even so I am up against the limits of my knowledge when it comes to eSecurity.  For instance, how do I know that my machine has not been taken over, that what I consider my machine is or is not a virtual machine running on my hardware but under control of whoever?  How do I know  that there is no funky logic in the chips in my machine which is sending everything I type to some hostile foreign power?  Etc?

The problem is so complex overall that when someone actually tries a tool then it should just work.  I am glad to see, therefore, that cooperq added this to a list of bugs to fix.  Thanks for that.

Jeff B.

PS: Got any foolproof virtual machine detectors out there?

**Comment by cooperq** [comment]
@not-so-gnubie can you please send me a screenshot of privacy badger's settings on google maps for you?

**Comment by not-so-gnubie** [comment]
The list is 11 items long so there are two screenshots which also show the blank maps.

![my privacy badger settings for maps google com 1](https://cloud.githubusercontent.com/assets/13799513/9351719/d7c77ac6-4629-11e5-99bf-13f3d1bc5159.jpg)
![my privacy badger settings for maps google com 2](https://cloud.githubusercontent.com/assets/13799513/9351720/d7cefb2a-4629-11e5-8819-41144a76f720.jpg)

**Comment by SwartzCr** [comment]
so the issue is the blockage of maps.googleapis.com, which should be okay due to the @@||googleapis.com^$third-party
on line 1 of the cookieblocklist (though why there are other subdomains for googleapis.com on that list I'm not sure)
This is the second googleapis.com issue we've seen recently (see #516)
We are hoping to fix this, but it is an issue with cookieblocking in general

**Comment by SwartzCr** [comment]
I'm actually going to close this in favor of #516, feel free to add any new information there
(and thanks for being such a helpful bug reporter! but we've just got to fight the issue page clutter!)
