### ISSUE TITLE
craigslist.fi layout blocked

### ISSUE THREAD

**Issue by anonsubmitter** [EFForg/privacybadgerfirefox#521]
The layout on http://helsinki.craigslist.fi/ is blocked. Changing www.craigslist.org from being completely blocked (red) to just blocking cookies from the domain (yellow) fixes this.

**Comment by SwartzCr** [comment]
this is a classic problem where a country TLD is blocking the resource store which is using the origin country's tld
since they're coming from different domains PB thinks that it should be blocked
BUT THE REAL QUESTION is why is it getting blocked when it's not being loaded from outside of craigslist.fi? since that's not going to be multiple domains, and I don't think changing subdomains should trigger this, this seems like more than just a site bug to me but possibly a bug in total PB workflow

**Comment by cooperq** [comment]
Wait, they are saying that craiglist.org gets blocked on craigslist.fi I don't understand how that is a bug. Shouldn't that be the expected behavior since they are different domains?
