### ISSUE TITLE
Add pref to disable yellowlist

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerfirefox#629]
Please consider adding a "disable yellowlist" ("block all trackers") option for people, who do not want compromises with trackers or would like to allow every one of them manually. Overriding about 500 sites is a tough task.

**Comment by jawz101** [comment]
The whole purpose is to let content through but block the cookie.  Like go to YouTube and turn ytimg.com to red.  The whole page jacks up because Google likely splits up content on different servers so it remains a fast website.
If I play with ad and script blockers long enough I eventually have to white list a bunch of this stuff anyways.
I use Privacy Badger in conjunction with ad blockers and script blockers if I want to limit content but the function is there to still strip any potential trackers out.

**Comment by cooperq** [comment]
We put things on the yellow list because if they are not there many websites break. Like @jawz101 said, the yellowlist is their to prevent things from tracking you without breaking websites. Allowing users to disable the yellowlist entirely would be giving them a gun to shoot themselves in the foot with. I'm worried that this option would be confusing and frustrating for many users.
