### ISSUE TITLE
Use of Privacy Badger on top of uBlock Origin

### ISSUE THREAD

**Issue by harshanvn** [EFForg/privacybadgerfirefox#691]
I would like to know what is the added benefit of using Privacy Badger, if one is using an **_uBlock Origin_**, and as configured below -

- Set Firefox to **deny** 3rd party cookies.
- Set uBlock Origin to **Medium Blocking** mode (i.e., it blocks 3rd Party Scripts and Frames)
- Set to use Experimental **Redirect** Filters (this helps to foil certain tracking scripts completely with out any exceptions. See <a href="https://github.com/gorhill/uBlock/blob/db74ea310b966def35e8422d617b0beae59994b8/assets/ublock/redirect-resources.txt">here</a>)
- Add many other 3rd party lists.

**Note**: This is not about A Vs B. I am just trying to evaluate whether i should really add PB on top of my uBlock Origin or not. If you believe i would benefit in adding it, can you please give me hard and concrete examples, so i can evaluate myself..

**Comment by cooperq** [comment]
So I would say that there are two extra advanatges that privacy badger could give you here;
1. Social media widget replacement - not sure if ublock does this or not, (or maybe your social media widgets are already entirely blocked by ublock) but if they are not privacy badger can add an extra layer of protection. 
2. Cookie blocking - we block cookies and referers from many things that would otherwise not normally be blocked i.e. google maps ; this can add an extra layer of privacy to your browsing. 

If you think that either one of these is good then I would say use them together, otherwise don't worry about it.

**Comment by harshanvn** [comment]
Thanks for your prompt input, Appreciate it!!

> Social media widget replacement

I believe this can be taken care by uBlock. Not an issue. If its not blocked, a filter rule will take care of it.

> Cookie blocking - we block cookies and referers

 Cookies for me are already taken care by firefox built-in settings. reg. Referrer, i will review.

Thanks! I will continue using uBlock Origin only at this moment.
