### ISSUE TITLE
Unsigned PB blocked on Firefox 43 ...

### ISSUE THREAD

**Issue by fizicsfred** [EFForg/privacybadgerfirefox#695]
With version 43 of Firefox, unsigned extensions are disabled (which included PrivacyBadger v1.0.1). Need a SIGNED version for Firefox! ... PLEASE!!!

THANKS!!!

**Comment by Yeow** [comment]
Please create a signed version for Firefox.  FF 43 disabled Privacy Badger.  It is a vital tool with no parallel.

Thanks

**Comment by trvrfrd** [comment]
v1.0.5 is available on the [EFF site](https://www.eff.org/privacybadger) and installs fine for me on FF 45, which I assume also requires extensions to be signed. Have you tried updating the extension or removing and adding it again?

**Comment by fizicsfred** [comment]
Finally got it to update. Works Great!!! 
Thanks Again!

**Comment by Yeow** [comment]
Good Morning,

Thanks for your reply.  However, I still cannot install Privacy Badger on
Fire Fox 43.0.1 from the EFF site.  The message says that Fire Fox will not
allow it to be installed.  When I repeat the process I get a message that
says there is a connection failure.  The EFF FAQs says that message may be
due to AVAST anti-virus.  I am not running AVAST nor have I ever run it.

Is there an alternate site with a signed version of Privacy Badger?

Best Regards,
Dave Williams

**Comment by Yeow** [comment]
Good Morning Again,

I pulled a dummy.  I couldn't download Privacy Badger from EFF, as my last
e-mail said.  Then it dawned on me, maybe I need to check and see if I can
download it from FF add-ons.  I did and it works.  Thanks for your help.

Best Regards,
Dave Williams
