### ISSUE TITLE
Privacy Badger 1.9.2?

### ISSUE THREAD

**Issue by centuryplant** [EFForg/privacybadgerfirefox#820]
Firefox wants me to update to a new version of Privacy Badger, 1.9.2.  I can't find any patch notes for that version, and here on Github the latest appears to be 1.8.2.

Is this update legitimate?  What changed?

**Comment by cooperq** [comment]
Hey sorry I was out of town, this update is legitimate.  I forgot to push the tags and add the changelog notes because there was so much back and forth with mozilla about this release. I have now pushed the tags and added the changelog on AMO. The main purpouse of this release was to migrate data to a place where the upcoming web extensions release will be able to access it. Here is the changelog:

1.9.2                             (2016-11-4)
  * Only run migration script on unload

1.9.1                             (2016-11-2)
  * Upgrade Jquery for mozilla validation
  * Only migrate data every 24 hours so as to not impact performance

1.9                               (2016-11-1)
  * Preparing for transition to web extensions
  * Changes to Chinese and Spanish translations
